第 10 章　错误处理与异常

[TOC]

##10.1　关于错误处理
在程序执行的过程中，通常会有以下错误发生：
数据错误
系统错误
程序错误

错误的处理：
排除错误的原因
忽略错误
恢复错误发生前的状态
重试一次
终止程序

而至于实际应该采取何种处理，则要根据程序代码的规模、应用程序的性质来决定，不能一概而论。但是，对于可预期的错误，我们需要留意以下两点：
是否破坏了输入的数据，特别是人工制作的数据。
是否可以对错误的内容及其原因做出相应的提示。

##10.2　异常处理
在程序执行的过程中，如果程序出现了错误就会发生异常。异常发生后，程序会暂时停止运行，并寻找是否有对应的异常处理程序。如果有则执行，如果没有，程序就会显示类似以下信息并终止运行。

异常处理有以下优点：
程序不需要逐个确认处理结果，也能自动检查出程序错误
会同时报告发生错误的位置，便于排查错误
正常处理与错误处理的程序可以分开书写，使程序便于阅读


##10.3　异常处理的写法
Ruby 中使用 begin ～ rescue ～ end 语句描述异常处理。

begin
　可能会发生异常的处理
rescue
　发生异常时的处理
end

在 Ruby 中，异常及其相关信息都是被作为对象来处理的。在 rescue 后指定变量名，可以获得异常对象。

begin
　可能会发生异常的处理
rescue => 引用异常对象的变量
　发生异常时的处理
end

即使不指定变量名，Ruby 也会像表 10.1 那样把异常对象赋值给变量 $!。不过，把变量名明确地写出来会使程序更加易懂。

$!：最后发生的异常（异常对象）
$@：最后发生的异常的位置信息

异常对象的方法
class：异常的种类
message：异常信息
backtrace：异常发生的位置信息（$@ 与 $!.backtrace 是等价的）

```
ltotal=0                             # 行数合计
wtotal=0                             # 单词数合计
ctotal=0                             # 字数合计
ARGV.each do |file|
  begin
    input = File.open(file)          # 打开文件（A）
    l=0                              # file 内的行数
    w=0                              # file 内的单词数
    c=0                              # file 内的字数
    input.each_line do |line|
      l += 1
      c += line.size
      line.sub!(/^\s+/, "")          # 删除行首的空白符
      ary = line.split(/\s+/)        # 用空白符分解
      w += ary.size
    end
    input.close                      # 关闭文件
    printf("%8d %8d %8d %s\n", l, w, c, file)  # 整理输出格式
    ltotal += l
    wtotal += w
    ctotal += c
  rescue => ex
    print ex.message, "\n"           # 输出异常信息（B）
    end
end

printf("%8d %8d %8d %s\n", ltotal, wtotal, ctotal, "total")
```

##10.4　后处理
不管是否发生异常都希望执行的处理，在 Ruby 中可以用 ensure 关键字来定义。

begin
　有可能发生异常的处理
rescue => 变量
　发生异常后的处理
ensure
　不管是否发生异常都希望执行的处理
end
```
def copy(from, to)
  src = File.open(from)         # 打开原文件from（A）
  begin
    dst = File.open(to, "w")    # 打开目标文件to（B）
    data = src.read
    dst.write(data)
    dst.close
  ensure
    src.close                   # （C）
  end
end
```

##10.5　重试
在 rescue 中使用 retry 后，begin 以下的处理会再重做一遍。

```
file = ARGV[0]
begin
  io = File.open(file)
rescue
  sleep 10
  retry
end

data = io.read
io.close
```
##10.6　rescue 修饰符
与 if 修饰符、unless 修饰符一样，rescue 也有对应的修饰符。
表达式 1 rescue 表达式 2

如果表达式 1 中发生异常，表达式 2 的值就会成为整体表达式的值。也就是说，上面的式子与下面的写法是等价的：

begin
　表达式 1
rescue
　表达式 2
end

我们再来看看下面的例子：
```
n = Integer(val) rescue 0
```
Integer 方法当接收到 "123" 这种数值形式的字符串参数时，会返回该字符串表示的整数值，而当接收到 "abc" 这种非数值形式的字符串参数时，则会抛出异常（在判断字符串是否为数值形式时经常用到此方法）。在本例中，如果 val 是不正确的数值格式，就会抛出异常，而 0 则作为 = 右侧整体表达式的返回值。像这样，这个小技巧经常被用在不需要过于复杂的处理，只是希望简单地对变量赋予默认值的时候。

##10.7　异常处理语法的补充
如果异常处理的范围是整个方法体，也就是说整个方法内的程序都用 begin ～ end 包含的话，我们就可以省略 begin 以及 end，直接书写 rescue 与 ensure 部分的程序。

def foo
　方法体
rescue => ex
　异常处理
ensure
　后处理
end

同样，我们在类定义中也可以使用 rescue 以及 ensure。但是，如果类定义途中发生异常，那么异常发生部分后的方法定义就不会再执行了，因此一般我们不会在类定义中使用它们。

class Foo
　类定义
rescue => ex
　异常处理
ensure
　后处理
end
##10.8　指定需要捕捉的异常
当存在多个种类的异常，且需要按异常的种类分别进行处理时，我们可以用多个 rescue 来分开处理。

begin
　可能发生异常的处理
rescue Exception1, Exception2 => 变量
　对Exception1 或者Exception2 的处理
rescue Exception3 => 变量
　对Exception3 的处理
rescue
　对上述异常以外的异常的处理
end

通过直接指定异常类，可以只捕捉我们希望处理的异常。
```
file1 = ARGV[0]
file2 = ARGV[1]
begin
  io = File.open(file1)
rescue Errno::ENOENT, Errno::EACCES
  io = File.open(file2)
end

```

##10.9　异常类
Ruby 中所有的异常都是 Exception 类的子类，并根据程序错误的种类来定义相应的异常。
![](https://box.kancloud.cn/2015-10-26_562e01e92ba32.png)

##10.10　主动抛出异常
使用 raise 方法，可以使程序主动抛出异常。在基于自己判定的条件抛出异常，或者把刚捕捉到的异常再次抛出并通知异常的调用者等情况下，我们会使用 raise 方法。

raise 方法有以下 4 种调用方式：
raise message：抛出 RuntimeError 异常，并把字符串作为 message 设置给新生成的异常对象。

raise 异常类：抛出指定的异常。

raise 异常类，message:抛出指定的异常，并把字符串作为 message 设置给新生成的异常对象。

raise:在 rescue 外抛出 RuntimeError。在 rescue 中调用时，会再次抛出最后一次发生的异常（$!）。